# cloud-config
hostname: ubuntu
manage_etc_hosts: True
system_info:
  default_user:
    name: cisco
password: cisco
chpasswd: { expire: False }
ssh_pwauth: True
ssh_authorized_keys:
  - your-ssh-pubkey-line-goes-here

timezone: Asia/Tokyo

locale: ja_JP.utf8

# run apt-get update
# default false
package_update: true

# default false
package_upgrade: true

# packages
packages:
  - git

ansible:
  install_method: pip
  pull:
    url: "https://github.com/takamitsu-iida/frr-on-cml.git"
    playbook_name: ubuntu.yml











# add packages
packages:
  # needed to compile FRR
  - git
  - autoconf
  - automake
  - libtool
  - make
  - libreadline-dev
  - texinfo
  - pkg-config
  - libpam0g-dev
  - libjson-c-dev
  - bison
  - flex
  - libc-ares-dev
  - python3-dev
  - python3-sphinx
  - install-info
  - build-essential
  - libsnmp-dev
  - perl
  - libcap-dev
  - libelf-dev
  - libunwind-dev
  - protobuf-c-compiler
  - libprotobuf-c-dev

  # needed to compile libyang
  - libgrpc++-dev
  - protobuf-compiler-grpc

  # needed to use rollback
  - libsqlite3-dev

  # optional
  - libzmq5
  - libzmq3-dev


write_files:
  - path: /etc/netplan/50-cloud-init.yaml
    content: |
      network:
        version: 2
        ethernets:
          ens2:
            dhcp4: true

runcmd:

  - |
    cat - << 'EOS' >> /etc/bash.bashrc
    rsz () if [[ -t 0 ]]; then local escape r c prompt=$(printf '\e7\e[r\e[999;999H\e[6n\e8'); IFS='[;' read -sd R -p j"$prompt" escape r c; stty cols $c rows $r; fi
    rsz
    EOS
