---

- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    packages:
      - git
      - autoconf
      - automake
      - libtool
      - make
      - libreadline-dev
      - texinfo
      - pkg-config
      - libpam0g-dev
      - libjson-c-dev
      - bison
      - flex
      - libc-ares-dev
      - python3-dev
      - python3-sphinx
      - install-info
      - build-essential
      - libsnmp-dev
      - perl
      - libcap-dev
      - libelf-dev
      - libunwind-dev
      - protobuf-c-compiler
      - libprotobuf-c-dev

      # needed to compile libyang
      - libgrpc++-dev
      - protobuf-compiler-grpc

      # needed to use rollback
      - libsqlite3-dev

      # optional
      - libzmq5
      - libzmq3-dev

  roles:
    - apt
