---

#
# install libyang
#

- name: git clone libyang
  ansible.builtin.git:
    repo: "{{ libyang_repo_url }}"
    dest: /tmp
    version: "{{ libyang_version }}"

- name: create build directory
  ansible.builtin.file:
    path: /tmp/libyang/build
    state: directory

- name: execute cmake
  ansible.builtin.command: cmake --install-prefix /usr -D CMAKE_BUILD_TYPE:String="Release" ..
  args:
    src: /tmp/libyang/build

- name: execute make
  community.general.make:
    chdir: /tmp/libyang/build

- name: execute make install
  community.general.make:
    target: install
    chdir: /tmp/libyang/build

- name: create group 'frr'
  ansible.builtin.group:
    name: frr
    state: present
    gid: 92

- name: create group 'frrvty'
  ansible.builtin.group:
    name: frrvty
    state: present
    gid: 85

- name: Add user 'frr'
  ansible.builtin.user:
    name: frr
    state: present
    comment: FRR suite
    shell: /sbin/nologin
    create_home: true
    home: /var/run/frr
    groups:
      - frr
      - frrvty

- name: git clone frr
  ansible.builtin.git:
    repo: "{{ frr_repo_url }}"
    dest: /tmp

- name: execute bootstrap.sh
  ansible.builtin.command: ./bootstrap.sh
  args:
    src: /tmp/frr

- name: execute configure
  ansible.builtin.command:
    ./configure
    --prefix=/usr
    --includedir=/usr/include
    --bindir=/usr/bin
    --sbindir=/usr/lib/frr
    --libdir=/usr/lib/frr
    --libexecdir=/usr/lib/frr
    --sysconfdir=/etc
    --localstatedir=/var
    --with-moduledir=/usr/lib/frr/modules
    --enable-configfile-mask=0640
    --enable-logfile-mask=0640
    --enable-snmp=agentx
    --enable-multipath=64
    --enable-user=frr
    --enable-group=frr
    --enable-vty-group=frrvty
    --with-pkg-git-version
    --with-pkg-extra-version=-MyOwnFRRVersion
  args:
    src: /tmp/frr

- name: execute make
  community.general.make:
    chdir: /tmp/frr

- name: execute make install
  community.general.make:
    target: install
    chdir: /tmp/frr

- name: execute install
  ansible.builtin.command: install -m 775 -o frr -g frr -d /var/log/frr
  args:
    src: /tmp/frr

- name: execute install
  ansible.builtin.command: install -m 775 -o frr -g frrvty -d /etc/frr
  args:
    src: /tmp/frr

- name: execute install
  ansible.builtin.command: install -m 640 -o frr -g frrvty tools/etc/frr/vtysh.conf /etc/frr/vtysh.conf
  args:
    src: /tmp/frr

- name: execute install
  ansible.builtin.command: install -m 640 -o frr -g frr tools/etc/frr/frr.conf /etc/frr/frr.conf
  args:
    src: /tmp/frr

- name: execute install
  ansible.builtin.command: install -m 640 -o frr -g frr tools/etc/frr/daemons.conf /etc/frr/daemons.conf
  args:
    src: /tmp/frr

- name: execute install
  ansible.builtin.command: install -m 640 -o frr -g frr tools/etc/frr/daemons /etc/frr/daemons
  args:
    src: /tmp/frr

- name: change kernel configuration
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv4.ip_forward='
    line: net.ipv4.ip_forward=1

- name: change kernel configuration
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv6.conf.all.forwarding='
    line: net.ipv6.conf.all.forwarding=1

- name: execute install
  ansible.builtin.command: install -m 644 tools/frr.service /etc/systemd/system/frr.service
  args:
    src: /tmp/frr/frr

- name: Make sure a service unit is running
  ansible.builtin.systemd_service:
    enabled: true
    name: frr
