---

#
# install libyang
#

- name: Execute git clone libyang
  ansible.builtin.git:
    repo: "{{ libyang_repo_url }}"
    dest: /tmp/libyang
    version: "{{ libyang_version }}"

- name: Create build directory
  ansible.builtin.file:
    path: /tmp/libyang/build
    state: directory

- name: Execute cmake
  ansible.builtin.command:
    cmd: 'cmake --install-prefix /usr -D CMAKE_BUILD_TYPE:String="Release" ..'
  args:
    chdir: /tmp/libyang/build

- name: Execute make
  community.general.make:
    chdir: /tmp/libyang/build

- name: Execute make install
  community.general.make:
    target: install
    chdir: /tmp/libyang/build

- name: Create group 'frr'
  ansible.builtin.group:
    name: frr
    state: present
    gid: 92

- name: Create group 'frrvty'
  ansible.builtin.group:
    name: frrvty
    state: present
    gid: 85

- name: Add user 'frr'
  ansible.builtin.user:
    name: frr
    state: present
    comment: FRR suite
    shell: /sbin/nologin
    create_home: true
    home: /var/run/frr
    groups:
      - frr
      - frrvty

- name: Execute git clone frr
  ansible.builtin.git:
    repo: "{{ frr_repo_url }}"
    dest: /tmp/frr

- name: Execute bootstrap.sh
  ansible.builtin.command:
    cmd: ./bootstrap.sh
  args:
    chdir: /tmp/frr

- name: Execute configure
  ansible.builtin.command:
    cmd: |-
      ./configure
      --prefix=/usr
      --includedir=/usr/include
      --bindir=/usr/bin
      --sbindir=/usr/lib/frr
      --libdir=/usr/lib/frr
      --libexecdir=/usr/lib/frr
      --sysconfdir=/etc
      --localstatedir=/var
      --with-moduledir=/usr/lib/frr/modules
      --enable-configfile-mask=0640
      --enable-logfile-mask=0640
      --enable-snmp=agentx
      --enable-multipath=64
      --enable-user=frr
      --enable-group=frr
      --enable-vty-group=frrvty
      --with-pkg-git-version
#      --with-pkg-extra-version=-MyOwnFRRVersion
  args:
    chdir: /tmp/frr

- name: Execute make
  community.general.make:
    chdir: /tmp/frr

- name: Execute make install
  community.general.make:
    target: install
    chdir: /tmp/frr

- name: Execute install
  ansible.builtin.command:
    cmd: install -m 775 -o frr -g frr -d /var/log/frr
  args:
    chdir: /tmp/frr

- name: Execute install
  ansible.builtin.command:
    cmd: install -m 775 -o frr -g frrvty -d /etc/frr
  args:
    chdir: /tmp/frr

- name: Execute install
  ansible.builtin.command:
    cmd: install -m 640 -o frr -g frrvty tools/etc/frr/vtysh.conf /etc/frr/vtysh.conf
  args:
    chdir: /tmp/frr

- name: Execute install
  ansible.builtin.command:
    cmd: install -m 640 -o frr -g frr tools/etc/frr/frr.conf /etc/frr/frr.conf
  args:
    chdir: /tmp/frr

- name: Execute install
  ansible.builtin.command:
    cmd: install -m 640 -o frr -g frr tools/etc/frr/daemons.conf /etc/frr/daemons.conf
  args:
    chdir: /tmp/frr

- name: Execute install
  ansible.builtin.command:
    cmd: install -m 640 -o frr -g frr tools/etc/frr/daemons /etc/frr/daemons
  args:
    chdir: /tmp/frr

- name: Execute install
  ansible.builtin.command:
    cmd: install -m 644 tools/frr.service /etc/systemd/system/frr.service
  args:
    chdir: /tmp/frr

- name: Change kernel configuration
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv4.ip_forward='
    line: net.ipv4.ip_forward=1

- name: Change kernel configuration
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv6.conf.all.forwarding='
    line: net.ipv6.conf.all.forwarding=1

- name: Start frr daemon on start ubuntu
  ansible.builtin.systemd_service:
    enabled: true
    name: frr

- name: Make sure a service unit is running
  ansible.builtin.systemd_service:
    state: started
    name: frr

#- name: Change frr configuration
#  ansible.builtin.lineinfile:
#    path: /etc/frr/daemons
#    regexp: '^fabricd=no'
#    line: fabricd=yes

- name: Remove cloud-init directory
  ansible.builtin.file:
    path: /var/lib/cloud/
    state: absent
